# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 18:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Audits', '0011_auto_20160104_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Auditor',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
