# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audits', '0013_auto_20160220_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credential', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
