# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audits', '0016_auto_20160312_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aaudits', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaudits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audit',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uaudits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='credentialsmodel',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credential', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
