# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audits', '0017_auto_20160312_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsmodel',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credential', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
