# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Audits', '0018_auto_20160312_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_role', models.BooleanField()),
                ('has_sync', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='audit',
            name='freq',
            field=models.CharField(blank=True, choices=[(b'DAYLY', 'Dayly'), (b'WEEKLY', 'Weekly'), (b'MONTHLY', 'Monthly'), (b'YEARLY', 'Yearly')], max_length=100, null=True, verbose_name='Period'),
        ),
    ]
